script: "cd test/dummy && bundle exec rails g clover_cms:articulate:install && cd ../../ && bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.2
  - jruby
  - ree
notifications:
  recipients:
    - enrique@cloverinteractive.com
    - alejandro@cloverinteractive.com


